# Use this Blueprint to deploy kokoro on Render as a web
#
# This Blueprint uses free instance types (specified by
# `plan`) for both the web service and the database. You
# can upgrade to paid instance types at any time to
# increase resources.

services:
  - type: web
    plan: free
    # This is the runtime for services that pull a prebuilt Docker image
    runtime: image
    # You can give the service any name
    name: kokoro-tts
    image:
      # Pulls the kokoro image tagged as latest from Docker Hub
      url: docker.io/dustynv/kokoro-tts:fastapi-r36.4.0


